menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}


study:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/'}

